/**
 * Entity CRUD definitions for GenericCrudPanel.
 * primaryKey: column used for update/delete
 * columns: { key, label, type?, editable?, required?, options? }
 */

async function loadDonationRows(supabase) {
  const { data: donations, error } = await supabase
    .from('donations')
    .select('*')
    .order('donation_date', { ascending: false })
    .limit(200)

  if (error) throw new Error(error.message)
  if (donations?.length) return donations

  const { data: campaigns, error: campErr } = await supabase
    .from('campaigns')
    .select('campaign_id, title, shelter_id, current_amount, created_at')
    .gt('current_amount', 0)
    .eq('is_deleted', false)
    .order('created_at', { ascending: false })
    .limit(200)

  if (campErr) throw new Error(campErr.message)

  return (campaigns || []).map((campaign) => ({
    donation_id: campaign.campaign_id,
    campaign_id: campaign.campaign_id,
    campaign_title: campaign.title,
    shelter_id: campaign.shelter_id,
    user_id: null,
    amount: campaign.current_amount,
    donation_date: campaign.created_at,
    _from_campaign: true,
  }))
}

export const ENTITY_CONFIGS = {
  profiles: {
    table: 'profiles',
    primaryKey: 'user_id',
    title: 'User Profiles',
    description: 'Manage all registered platform accounts and assign roles (Admin, Clinic, Shelter, or Adopter).',
    orderBy: { column: 'user_name', ascending: true },
    limit: 300,
    columns: [
      { key: 'user_id', label: 'User ID', editable: false },
      { key: 'user_name', label: 'Name', required: true },
      { key: 'email', label: 'Email' },
      { key: 'phone_number', label: 'Phone' },
      {
        key: 'user_type',
        label: 'Type',
        type: 'select',
        options: ['Adopter', 'Clinic', 'Shelter', 'Admin'],
      },
      { key: 'avatar_url', label: 'Avatar URL' },
    ],
  },
  adopter_profiles: {
    table: 'adopter_profiles',
    primaryKey: 'adopter_id',
    title: 'Adopter Profiles',
    description: 'Extended profiles for pet adopters, including housing and pet ownership details.',
    orderBy: { column: 'adopter_id', ascending: false },
    columns: [
      { key: 'adopter_id', label: 'ID', editable: false },
      { key: 'user_id', label: 'User ID' },
      { key: 'housing_type', label: 'Housing' },
      { key: 'has_other_pets', label: 'Other Pets', type: 'boolean' },
    ],
  },
  clinics: {
    table: 'clinics',
    primaryKey: 'clinic_id',
    title: 'Veterinary Clinics',
    description: 'Partner veterinary clinics providing medical services on the platform.',
    orderBy: { column: 'name', ascending: true },
    columns: [
      { key: 'clinic_id', label: 'ID', editable: false },
      { key: 'name', label: 'Name', required: true },
      { key: 'location', label: 'Location' },
      { key: 'phone', label: 'Phone' },
      { key: 'owner_id', label: 'Owner User ID' },
      { key: 'logo_url', label: 'Logo URL' },
      { key: 'rating', label: 'Rating', type: 'number' },
    ],
  },
  shelter_profiles: {
    table: 'shelter_profiles',
    primaryKey: 'shelter_id',
    title: 'Animal Shelters',
    description: 'Registered shelter organizations managing adoptions and fundraising.',
    orderBy: { column: 'org_name', ascending: true },
    columns: [
      { key: 'shelter_id', label: 'ID', editable: false },
      { key: 'org_name', label: 'Organization', required: true },
      { key: 'user_id', label: 'Owner User ID' },
      { key: 'license_number', label: 'License' },
      { key: 'is_verified', label: 'Verified', type: 'boolean' },
      { key: 'logo_url', label: 'Logo URL' },
      { key: 'rating', label: 'Rating', type: 'number' },
    ],
  },
  shops: {
    table: 'shops',
    primaryKey: 'shop_id',
    title: 'Pet Shops',
    description: 'Retail partners selling pet products through the PetPals marketplace.',
    orderBy: { column: 'name', ascending: true },
    columns: [
      { key: 'shop_id', label: 'ID', editable: false },
      { key: 'name', label: 'Name', required: true },
      { key: 'location', label: 'Location' },
      { key: 'phone', label: 'Phone' },
      { key: 'owner_id', label: 'Owner User ID' },
      { key: 'logo_url', label: 'Logo URL' },
      { key: 'rating', label: 'Rating', type: 'number' },
    ],
  },
  pets: {
    table: 'pets',
    primaryKey: 'pet_id',
    title: 'Pet Registry',
    description: 'All animals registered on the platform across shelters, clinics, and owners.',
    orderBy: { column: 'created_at', ascending: false },
    columns: [
      { key: 'pet_id', label: 'ID', editable: false },
      { key: 'name', label: 'Name', required: true },
      { key: 'species', label: 'Species' },
      { key: 'breed', label: 'Breed' },
      { key: 'age', label: 'Age', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Available', 'Active', 'Healthy', 'Sick', 'Adopted', 'Deceased', 'Recovery', 'Archived'],
      },
      { key: 'owner_id', label: 'Owner ID' },
      { key: 'shelter_id', label: 'Shelter ID' },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'avatar_url', label: 'Avatar URL' },
      { key: 'collar_uuid', label: 'Collar UUID' },
    ],
  },
  applications: {
    table: 'applications',
    primaryKey: 'application_id',
    title: 'Adoption Applications',
    description: 'Review and manage adoption requests submitted by prospective pet owners.',
    orderBy: { column: 'submission_date', ascending: false },
    columns: [
      { key: 'application_id', label: 'ID', editable: false },
      { key: 'pet_id', label: 'Pet ID' },
      { key: 'adopter_id', label: 'Adopter ID' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Under Review', 'Approved', 'Rejected'],
      },
      { key: 'match_score', label: 'Match Score', type: 'number' },
    ],
  },
  appointments: {
    table: 'appointments',
    primaryKey: 'appointment_id',
    title: 'Veterinary Appointments',
    description: 'Scheduled clinic visits, consultations, and follow-up appointments.',
    orderBy: { column: 'appointment_date', ascending: false },
    columns: [
      { key: 'appointment_id', label: 'ID', editable: false },
      { key: 'user_id', label: 'User ID' },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'appointment_date', label: 'Date', type: 'datetime' },
      { key: 'reason', label: 'Reason' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Pending', 'Confirmed', 'Completed', 'Cancelled', 'Missed'],
      },
    ],
  },
  medical_records: {
    table: 'medical_records',
    primaryKey: 'record_id',
    title: 'Medical Records',
    description: 'Clinical visit history, diagnoses, and treatment plans for registered pets.',
    orderBy: { column: 'visit_date', ascending: false },
    columns: [
      { key: 'record_id', label: 'ID', editable: false },
      { key: 'pet_id', label: 'Pet ID' },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'visit_date', label: 'Visit Date', type: 'date' },
      { key: 'diagnosis', label: 'Diagnosis', required: true },
      { key: 'treatment', label: 'Treatment', type: 'textarea', required: true },
      { key: 'vet_name', label: 'Vet Name' },
      { key: 'attachment_url', label: 'Attachment URL' },
    ],
  },
  campaigns: {
    table: 'campaigns',
    primaryKey: 'campaign_id',
    title: 'Fundraising Campaigns',
    description: 'Shelter-led donation campaigns with goals, progress tracking, and end dates.',
    orderBy: { column: 'created_at', ascending: false },
    columns: [
      { key: 'campaign_id', label: 'ID', editable: false },
      { key: 'shelter_id', label: 'Shelter ID' },
      { key: 'title', label: 'Title', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'goal_amount', label: 'Goal (EGP)', type: 'number' },
      { key: 'current_amount', label: 'Raised (EGP)', type: 'number' },
      { key: 'end_date', label: 'End Date', type: 'datetime' },
      { key: 'is_deleted', label: 'Soft Deleted', type: 'boolean' },
    ],
  },
  donations: {
    table: 'donations',
    primaryKey: 'donation_id',
    title: 'Donations',
    description: 'Contributions to shelter fundraising campaigns. Shows per-donation records when available, or campaign totals raised when individual rows have not been recorded.',
    emptyMessage: 'No donations recorded yet. Contributions appear here when adopters donate to shelter campaigns.',
    orderBy: { column: 'donation_date', ascending: false },
    loadRows: loadDonationRows,
    canCreate: false,
    columns: [
      { key: 'donation_id', label: 'ID', editable: false },
      { key: 'campaign_title', label: 'Campaign', editable: false },
      { key: 'campaign_id', label: 'Campaign ID', editable: false },
      { key: 'shelter_id', label: 'Shelter ID', editable: false },
      { key: 'user_id', label: 'User ID', editable: false },
      { key: 'amount', label: 'Amount (EGP)', type: 'number', editable: false },
      { key: 'donation_date', label: 'Date', editable: false },
    ],
  },
  products: {
    table: 'products',
    primaryKey: 'product_id',
    title: 'Marketplace Products',
    description: 'Pet supplies and goods listed by partner shops in the PetPals store.',
    orderBy: { column: 'name', ascending: true },
    selectColumns: 'product_id,shop_id,name,price,stock_level,category,image_url',
    columns: [
      { key: 'product_id', label: 'ID', editable: false },
      { key: 'shop_id', label: 'Shop ID' },
      { key: 'name', label: 'Name', required: true },
      { key: 'price', label: 'Price (EGP)', type: 'number' },
      { key: 'stock_level', label: 'Stock', type: 'number' },
      { key: 'category', label: 'Category' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image_url', label: 'Image URL' },
    ],
  },
  orders: {
    table: 'orders',
    primaryKey: 'order_id',
    title: 'Commerce Orders',
    description: 'Customer purchase orders with shipping status and payment details.',
    orderBy: { column: 'order_date', ascending: false },
    columns: [
      { key: 'order_id', label: 'ID', editable: false },
      { key: 'user_id', label: 'User ID' },
      { key: 'shop_id', label: 'Shop ID' },
      { key: 'total_amount', label: 'Total (EGP)', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Processing', 'Shipped', 'Delivered', 'Cancelled'],
      },
      { key: 'shipping_address', label: 'Address', type: 'textarea' },
      { key: 'payment_method', label: 'Payment' },
    ],
  },
  order_items: {
    table: 'order_items',
    primaryKey: 'order_item_id',
    title: 'Order Line Items',
    description: 'Individual products and quantities within each commerce order.',
    orderBy: { column: 'order_item_id', ascending: false },
    columns: [
      { key: 'order_item_id', label: 'ID', editable: false },
      { key: 'order_id', label: 'Order ID' },
      { key: 'product_id', label: 'Product ID' },
      { key: 'quantity', label: 'Qty', type: 'number' },
      { key: 'sub_total', label: 'Subtotal', type: 'number' },
    ],
  },
  invoices: {
    table: 'invoices',
    primaryKey: 'invoice_id',
    title: 'Invoices',
    description: 'Billing documents issued by clinics and shops to platform clients.',
    orderBy: { column: 'issue_date', ascending: false },
    columns: [
      { key: 'invoice_id', label: 'ID', editable: false },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'shop_id', label: 'Shop ID' },
      { key: 'client_id', label: 'Client ID' },
      { key: 'total_amount', label: 'Total', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Pending', 'Paid', 'Overdue', 'Cancelled'],
      },
      { key: 'payment_method', label: 'Payment Method' },
    ],
  },
  receipts: {
    table: 'receipts',
    primaryKey: 'receipt_id',
    title: 'Payment Receipts',
    description: 'Confirmed payment records linked to invoices and orders.',
    orderBy: { column: 'issued_at', ascending: false },
    columns: [
      { key: 'receipt_id', label: 'ID', editable: false },
      { key: 'receipt_number', label: 'Receipt #' },
      { key: 'source', label: 'Source' },
      { key: 'invoice_id', label: 'Invoice ID' },
      { key: 'order_id', label: 'Order ID' },
      { key: 'total_amount', label: 'Total (EGP)', type: 'number' },
      { key: 'payment_method', label: 'Payment' },
    ],
  },
  messages: {
    table: 'messages',
    primaryKey: 'message_id',
    title: 'Client Messages',
    description: 'Conversations between clinics, shelters, and adopters on the platform.',
    orderBy: { column: 'created_at', ascending: false },
    columns: [
      { key: 'message_id', label: 'ID', editable: false },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'shelter_id', label: 'Shelter ID' },
      { key: 'client_id', label: 'Client ID' },
      {
        key: 'sender',
        label: 'Sender',
        type: 'select',
        options: ['Clinic', 'Client', 'Shelter'],
      },
      { key: 'text', label: 'Message', type: 'textarea', required: true },
    ],
  },
  entity_reviews: {
    table: 'entity_reviews',
    primaryKey: 'review_id',
    title: 'Partner Reviews',
    description: 'User ratings and feedback for clinics, shelters, and shops.',
    orderBy: { column: 'created_at', ascending: false },
    columns: [
      { key: 'review_id', label: 'ID', editable: false },
      { key: 'user_id', label: 'User ID' },
      {
        key: 'entity_type',
        label: 'Entity Type',
        type: 'select',
        options: ['clinic', 'shelter', 'shop'],
      },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'rating', label: 'Rating', type: 'number' },
      { key: 'comment', label: 'Comment', type: 'textarea' },
    ],
  },
  clinic_procedures: {
    table: 'clinic_procedures',
    primaryKey: 'procedure_id',
    title: 'Clinic Procedures',
    description: 'Standard veterinary procedures and pricing offered by partner clinics.',
    columns: [
      { key: 'procedure_id', label: 'ID', editable: false },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'name', label: 'Name', required: true },
      { key: 'price', label: 'Price', type: 'number' },
    ],
  },
  clinic_staff: {
    table: 'clinic_staff',
    primaryKey: 'staff_id',
    title: 'Clinic Staff',
    description: 'Veterinary team members assigned to partner clinics and their roles.',
    columns: [
      { key: 'staff_id', label: 'ID', editable: false },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'user_id', label: 'User ID' },
      {
        key: 'role',
        label: 'Role',
        type: 'select',
        options: ['Head Vet', 'Associate Vet', 'Receptionist', 'Technician'],
      },
      { key: 'is_active', label: 'Active', type: 'boolean' },
    ],
  },
  inventory_items: {
    table: 'inventory_items',
    primaryKey: 'item_id',
    title: 'Clinic Inventory',
    description: 'Medical supplies, vaccines, and consumables stocked at partner clinics.',
    columns: [
      { key: 'item_id', label: 'ID', editable: false },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'item_name', label: 'Item', required: true },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        options: ['Medicine', 'Vaccine', 'Consumable', 'Retail'],
      },
      { key: 'current_stock', label: 'Stock', type: 'number' },
      { key: 'unit_price', label: 'Unit Price', type: 'number' },
    ],
  },
  clinic_expenses: {
    table: 'clinic_expenses',
    primaryKey: 'expense_id',
    title: 'Clinic Expenses',
    description: 'Operational costs and expenditures tracked by partner clinics.',
    columns: [
      { key: 'expense_id', label: 'ID', editable: false },
      { key: 'clinic_id', label: 'Clinic ID' },
      { key: 'description', label: 'Description', required: true },
      { key: 'amount', label: 'Amount', type: 'number' },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        options: ['Inventory Restock', 'Equipment', 'Rent', 'Other'],
      },
    ],
  },
  smart_collars: {
    table: 'smart_collars',
    primaryKey: 'collar_id',
    title: 'Smart Collars',
    description: 'GPS-enabled collars linked to registered pets for location tracking.',
    columns: [
      { key: 'collar_id', label: 'ID', editable: false },
      { key: 'pet_id', label: 'Pet ID' },
      { key: 'serial_number', label: 'Serial', required: true },
    ],
  },
  collar_sightings: {
    table: 'collar_sightings',
    primaryKey: 'collar_uuid',
    title: 'Collar Sightings',
    description: 'GPS location reports captured from active smart collars.',
    canCreate: false,
    columns: [
      { key: 'collar_uuid', label: 'Collar UUID', editable: false },
      { key: 'lat', label: 'Latitude', type: 'number' },
      { key: 'lon', label: 'Longitude', type: 'number' },
    ],
  },
  community_subreddits: {
    table: 'community_subreddits',
    primaryKey: 'subreddit_id',
    title: 'Community Discussions',
    description: 'Discussion categories and topics available in the community forum.',
    orderBy: { column: 'sort_order', ascending: true },
    columns: [
      { key: 'subreddit_id', label: 'ID', editable: false },
      { key: 'slug', label: 'Slug', required: true },
      { key: 'name', label: 'Display Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'icon_name', label: 'SF Symbol Icon' },
      { key: 'sort_order', label: 'Sort Order', type: 'number' },
      { key: 'is_active', label: 'Active', type: 'boolean' },
    ],
  },
  community_posts: {
    table: 'community_posts',
    primaryKey: 'post_id',
    title: 'Community Posts',
    description: 'User-published threads and articles within community discussions.',
    orderBy: { column: 'created_at', ascending: false },
    columns: [
      { key: 'post_id', label: 'ID', editable: false },
      { key: 'subreddit_id', label: 'Discussion ID' },
      { key: 'user_id', label: 'Author ID' },
      { key: 'title', label: 'Title', required: true },
      { key: 'body', label: 'Body', type: 'textarea', required: true },
      { key: 'image_url', label: 'Image URL' },
      { key: 'score', label: 'Score', type: 'number', editable: false },
      { key: 'comment_count', label: 'Comments', type: 'number', editable: false },
    ],
  },
  community_comments: {
    table: 'community_comments',
    primaryKey: 'comment_id',
    title: 'Community Comments',
    description: 'Replies and discussions posted on community threads.',
    orderBy: { column: 'created_at', ascending: false },
    columns: [
      { key: 'comment_id', label: 'ID', editable: false },
      { key: 'post_id', label: 'Post ID' },
      { key: 'user_id', label: 'User ID' },
      { key: 'body', label: 'Body', type: 'textarea', required: true },
      { key: 'score', label: 'Score', type: 'number', editable: false },
    ],
  },
  community_votes: {
    table: 'community_votes',
    primaryKey: 'vote_id',
    title: 'Community Votes',
    description: 'Upvotes and downvotes cast on community posts and comments.',
    canCreate: false,
    canEdit: false,
    orderBy: { column: 'created_at', ascending: false },
    columns: [
      { key: 'vote_id', label: 'ID', editable: false },
      { key: 'user_id', label: 'User ID', editable: false },
      { key: 'target_type', label: 'Target Type', editable: false },
      { key: 'target_id', label: 'Target ID', editable: false },
      { key: 'vote_value', label: 'Vote', type: 'number', editable: false },
    ],
  },
  user_personality_profiles: {
    table: 'user_personality_profiles',
    primaryKey: 'user_id',
    title: 'AI Personality Profiles',
    description: 'Lifestyle and preference data used for intelligent pet matching recommendations.',
    emptyMessage: 'No personality profiles yet. Profiles are created when adopters complete the pet-matching questionnaire in the mobile app.',
    orderBy: { column: 'user_id', ascending: true },
    columns: [
      { key: 'user_id', label: 'User ID' },
      { key: 'living_situation', label: 'Living Situation' },
      { key: 'activity_level', label: 'Activity Level' },
      { key: 'hours_home', label: 'Hours Home' },
      { key: 'experience', label: 'Experience' },
      { key: 'allergies', label: 'Allergies' },
      { key: 'household_type', label: 'Household' },
      { key: 'pet_priority', label: 'Pet Priority' },
    ],
  },
  appointment_usage: {
    table: 'appointment_usage',
    primaryKey: 'usage_id',
    title: 'Appointment Inventory Usage',
    description: 'Medical supplies consumed during veterinary appointments.',
    columns: [
      { key: 'usage_id', label: 'ID', editable: false },
      { key: 'appointment_id', label: 'Appointment ID' },
      { key: 'item_id', label: 'Inventory Item ID' },
      { key: 'quantity_used', label: 'Qty', type: 'number' },
    ],
  },
}

export function getEntityConfig(entityId) {
  return ENTITY_CONFIGS[entityId] || null
}
